name: groupys
services:
  groupys-db:
    image: pgvector/pgvector:pg18
    container_name: groupys-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - groupys_data_pg18:/var/lib/postgresql

  groupys-minio:
    image: quay.io/minio/minio
    container_name: groupys-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-changeme}
      MINIO_REGION: eu-central-1
      MINIO_BROWSER: "on"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"

  groupys-redis:
    image: redis:7-alpine
    container_name: groupys-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  groupys_data_pg18:
